apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harp-proxy.fullname" . }}
data:
  harp.yaml: |
    proxy:
      endpoints:
        {{- range .Values.endpoints }}
        - port: "{{ .port }}"
          name: "{{ .name }}"
          url: "{{ .url }}"
        {{- end }}

    {{ toYaml .Values.settings | nindent 4 }}
